### ISSUE TITLE
Issue with categorypages

### ISSUE THREAD

**Issue by Norwayman** [e107inc/vstore#10]
I have now put my 19 categories into just 7 main categories with the others inside of these categories.
What I am seeing is that there are still 3 pages of categories even though I have only 7 main categories with sub categories. And page 2 and 3 are empty. 

And....is it possible to inlude the script that Jimmi08 talked about here: e107inc/e107#1630 to avoid the differences when the images are not totally the same heigth or width?
![categoriespages](https://cloud.githubusercontent.com/assets/1757346/15481721/8743e258-20f1-11e6-974e-8bac2ee81a0f.JPG)

**Comment by Jimmi08** [comment]
That script shouldn't be in plugin but in theme itself. Each theme can use different solution for this. There is Masonry too.

**Comment by Norwayman** [comment]
@CaMer0n Yes this extra height makes it look a lot nicer when there are two lines in the category name.  And also the category pages are correct now. Thanks man!
![categoriespagesandnames](https://cloud.githubusercontent.com/assets/1757346/15485314/288eafc8-2104-11e6-9d8b-89deb85ae136.JPG)
