### ISSUE TITLE
Page 2 empty in vstore

### ISSUE THREAD

**Issue by Bepo2902** [e107inc/vstore#109]
I added a couple categories and items into the vstore. On purpose I entered more than 9 items in to get a second page. 
When I now press "next" I end up in the folder "Product Brands" and that is empty.

**Comment by SimSync** [comment]
@Bepo2902 How many items do you have in that category exactly? 9, 10 or more?

**Comment by SimSync** [comment]
@Bepo2902 Is this issue still open?

**Comment by Bepo2902** [comment]
I added at least 12. 
I had no time for uploading the new files yet. I will do so tonight and let you know.

**Comment by Bepo2902** [comment]
Same after updating the vstore files (and clearing cache / e107 and Browser)...

![page2](https://user-images.githubusercontent.com/46347624/54381818-9623c780-4686-11e9-9f17-d30c7bf828aa.PNG)

**Comment by Bepo2902** [comment]
Strangely enough, the 2nd page worked yesterday, but today it doesn't anymore. I can't imagine what I have changed, except, I added the menu, and the product variations. Weird. Different to the last screenshot is this time that I this time the Category is shown.
![page2new](https://user-images.githubusercontent.com/46347624/54878500-c0634b00-4e25-11e9-84b1-48ca6a783610.PNG)

**Comment by Bepo2902** [comment]
Any news/ideas?

**Comment by SimSync** [comment]
@Bepo2902 Please wait for the Pull Request to be merged. @CaMer0n reviewed my proposal and requested a change. I've already commited a change and i think, Cameron will review it as soon as he has time to do it. Once this is done, i'll post it here.

**Comment by SimSync** [comment]
@Bepo2902 The fix is now merged. Please update your installation. If it does not work with overwriting the files, remove the vstore folder from the server and upload the whole plugin. Uninstall and reinstall should be the last option... :wink:
