### ISSUE TITLE
New feature: Refunding 

### ISSUE THREAD

**Issue by SimSync** [e107inc/vstore#116]
Implement refunding for the payment gateways that support refunding.

**Comment by SimSync** [comment]
See PR: https://github.com/e107inc/vstore/pull/119

**Comment by SimSync** [comment]
PR #119 is merged now. Any testing is appreciated.

**Comment by Jimmi08** [comment]
Hm, I don't see point to refund directly from admin area but to set that order was refunded is great. But how to it manually? Yes, I understand message that I need send money manually but how to manually changes status?

 
![image](https://user-images.githubusercontent.com/5429548/59914050-d038fe00-9419-11e9-86ee-8fc8bb647f8d.png)
