### ISSUE TITLE
Tax not working with Dutch language..

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/vstore#120]
When using the Dutch language the tax cannot be entered, should be with a . but somehow it's changing in a , 

![vstore_vat_nl](https://user-images.githubusercontent.com/11962513/56413786-eba45300-6288-11e9-8b18-ac9527384850.jpg)

![vstore_vat_eng](https://user-images.githubusercontent.com/11962513/56413789-ed6e1680-6288-11e9-8032-3c4e8accc848.jpg)

![vstore_vat_nl_admin](https://user-images.githubusercontent.com/11962513/56413911-463daf00-6289-11e9-9594-2c4e51d6ff1b.jpg)

When a order is placed in English the tax is placed on the order, in the dutch language it's disappeared...

**Comment by Alex-e107nl** [comment]
Hi maybe it's something small, but when it's not working i cannot test it, has it something to do with the The floatval() function (is used to convert a value to a float) (admin_config_prefs.php line 168)?

Please Help!

**Comment by SimSync** [comment]
@Alex-e107nl Could you please test and verify if my fix really "fixes" ... 😉

**Comment by Alex-e107nl** [comment]
Hi,
ive tested it and it is possible now to enter taxes in the admin, but the only place it's showing when you buy a produkt is when you enter your details and the first screen after that gives the taxes, not in the mail, end not in the dashboard it is shown. Further, in the front all the decimals should be for example 50,00 instead of 50.00 (when working in another language for instance Dutch..)

Thx for your work, beside the translation (when are the strings going to be in a seperate language file?) it is a nice piece of software!

**Comment by SimSync** [comment]
@kreossino started with the translations, but i don't know how far he came. Maybe he can tell something about his progress.

Regarding the taxes... I see the include tax (VAT) on the shopping cart, on the checkout summary page, the dashboard order details page and also on the confirmation email(s)...
See attached images:
Shopping cart:
![grafik](https://user-images.githubusercontent.com/7572616/58944674-9cf04100-8782-11e9-8c3d-d4625dc39f8b.png)
Checkout summary:
![grafik](https://user-images.githubusercontent.com/7572616/58944690-a4174f00-8782-11e9-802e-43e10b55355c.png)
Dashboard order details:
![grafik](https://user-images.githubusercontent.com/7572616/58944697-abd6f380-8782-11e9-871a-e469a3bc0b54.png)
Confirmation email:
![grafik](https://user-images.githubusercontent.com/7572616/58944713-b09ba780-8782-11e9-883d-b91903c900b9.png)

**Comment by Alex-e107nl** [comment]
Hi Achim, should i install the Vstore plugin completely new then? You see more than i...

**Comment by SimSync** [comment]
Yes, i think that should help. Usually, you don't have to delete the db tables. But make sure you run the db update after you have reinstalled the store (and make sure to use the latest version from Github as i've added a commit this morning).

**Comment by Alex-e107nl** [comment]
Oke.... used the githubs of today of e107 and the Vstore plugin and i can tell you that when using the Dutch language in e107 it works now, i get the tax lines everywhere you expect it, so thx! 
The only 2 things now left is the € 29.95 where the dot should be a comma (,) in Dutch and the works in the admin side of the plugin but not at the front side and of course the translation.

**Comment by SimSync** [comment]
Please provide some screenshots.

**Comment by SimSync** [comment]
@Alex-e107nl What is the current status of this issue? Is it working now as expected or do you still have issues?

**Comment by Alex-e107nl** [comment]
Achim, tax works as it should now, buti cannot use the vstore with dots in stead of comma's i do not understand why it's working in the admin side but not changing in the front..

![vstore-dot](https://user-images.githubusercontent.com/11962513/59770324-22f2a880-92a8-11e9-9a8c-4d0433e095c6.jpg)

Maybe i should open a new thread?

Alex

**Comment by SimSync** [comment]
On admin you are working with comma, but at the front you have a period?
different users with different country settings, maybe?

**Comment by Alex-e107nl** [comment]
Achim, just downloaded the latest git of today.... and you did it!! Fantastic!!

![vstore-dot -2jpg](https://user-images.githubusercontent.com/11962513/59839804-8389f000-9351-11e9-8b0e-517b84d53831.JPG)

I wil start testing with Ideal / Mollie very soon, thx!!

Alex
