### ISSUE TITLE
report

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/vstore#126]
I tried to test this plugin.  I set Bank transfer. Product price 0.
This was the result when I tried to do checkout.

![image](https://user-images.githubusercontent.com/5429548/59603011-92319680-9108-11e9-802a-b3105f6fb406.png)

**Comment by SimSync** [comment]
@Jimmi08 Could you please post a screenshot of the payment gateway settings (bank)?
I did a test here with a product price 0 and bank as payment "gateway" and this worked as expected.

**Comment by Jimmi08** [comment]
I didn't fill the account number. It's not mandatory so it didn't occur me.
It worked now. Different error - this is why I am asking for messages if there is plugin dependency.  No warning that I have not plugin pdf installed. 
 
![image](https://user-images.githubusercontent.com/5429548/59608753-54d40580-9116-11e9-9dc8-395f8fe7d20d.png)

By the way, if you remove that basket from the main navigation, there is no information that product was added and no way how to check out.  Some normal menu would be nice.

Oh, and there are changes in core related to breadcrumbs.  
I had a problem that my theme use for class breadcrumb display: inline and it was broken. No possibility to add them as shortcode or style them because there is no class or id for custom styling.
I needed something like this:
```
		$bread = $frm->breadcrumb($array);
		$bread = "<div class='row vstore-breadcrumb'>".$bread."</div>";
		return $bread;
```
then I was to fix this with css.

But it's not important, I am just playing.

**Comment by SimSync** [comment]
@Jimmi08 Ths pdf issue is "known". I'll change this to be "off" by default and that someone can enable it in the invoice properties.
I'll will also have a look on the payment gateway options to check the required data during save.

**Comment by Jimmi08** [comment]
@SimSync Only discussion.
According to this:  https://github.com/e107inc/e107/issues/3835   if you put pdf plugin as required in plugin.xml, there should be some message.  Problem is that the pdf plugin is not able to download, there is no link with the information where to find it.  Neither in Readme file. 

If the value of the order is 0€ (item is free or there is coupon), it still ends with the invoice and awaiting payment. Is this correct?

**Comment by Jimmi08** [comment]
You are in check out page. You click in menu on clear cart. It's cleared, but you are still on check out page and you can continue...
