### ISSUE TITLE
breadcrumbs - changes in core from 2.2.2

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/vstore#132]
@CaMer0n 
 
This plugin needs to be fixed too. Removing breadcrumb from template doesn't solve the problem, there is different content.

![image](https://user-images.githubusercontent.com/5429548/59769638-d5c20700-92a6-11e9-8a67-abfdcbd53352.png)

**Comment by SimSync** [comment]
@Jimmi08 @CaMer0n Don't know, what's the issue here, or how to fix...

**Comment by Jimmi08** [comment]
@SimSync cameron has to add e_breadcrumbs addon to have correct values for magic breadcrumb shortcode (one shortcode for all site). If theme uses it, then plugin shortvode should be removed from plugin template. Only in this case, it's on theme developers. But e_br... Is missing now. I dont know how to do it. Ps. I am on mobile

**Comment by CaMer0n** [comment]
@SimSync There's some enhancements/changes in v2.2.2 which implements central handling of breadcrumbs in e107. Just send the breadcrumb array (as used by the form handler) to `e107::breadcrumb($array); ` and it will fix the issue.

**Comment by SimSync** [comment]
@Jimmi08 @CaMer0n Implemented the new breadcrumb method PR #147
