### ISSUE TITLE
FR - vstore category menu

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/vstore#142]
It would be nice to have category menu list (like news categories) with number of products in category.
@SimSync 
I could do template, but with your OOP way to create menu content is too much for me.  
Thanks
PS. If it is already there, I am blind.

**Comment by SimSync** [comment]
@Jimmi08 Do you mean the shop categories dropdown menu?
![grafik](https://user-images.githubusercontent.com/7572616/60176191-deba5780-9815-11e9-85bc-f3fc8c16d54f.png)

**Comment by Jimmi08** [comment]
Hi, this is good too, but I had on mind classic menu _menu.php you could put in sidebar or other menu area.

**Comment by CaMer0n** [comment]
I would call the sitelinks class from inside the vstore_category_menu.php file and then loop through with shortcodes/parsing and template.

**Comment by SimSync** [comment]
@Jimmi08 Just added a new menu for the categories. Also added a first template.

**Comment by Jimmi08** [comment]
Perfect as always. Thank you.

![image](https://user-images.githubusercontent.com/5429548/60421614-848d0e00-9bea-11e9-9451-b154ef65d6bb.png)

**Comment by SimSync** [comment]
@Jimmi08 Hmm... The selected cat (Test Category N.1) should be "highlighted" because the class "active" should have been added to the `<a>` tag. Here, in Bootstrap 3 this looks ok. So maybe this is an BS4 issue?

**Comment by Jimmi08** [comment]
maybe I did something wrong?
https://github.com/e107inc/bootstrap4/blob/master/templates/vstore/vstore_menu_template.php
Maybe is not "highlighted"  in list group format

**Comment by Jimmi08** [comment]
![image](https://user-images.githubusercontent.com/5429548/60425130-2c5a0a00-9bf2-11e9-80f6-a5aa4e39bc6f.png)

it's there
 Fixed, problem was in template
in this case it has to be with li tag.  

`<li class="list-group-item {MENU_CAT:active}"><a href="{MENU_CAT:url}" class="vstore-categories-item  ">`

but it doesn't support li active with a tag
![image](https://user-images.githubusercontent.com/5429548/60425340-9a063600-9bf2-11e9-8e59-1ca53c95a535.png)

**Comment by Jimmi08** [comment]
@Jimmi08 this is template issue 

With card layout you can't use your template (at least in actual bootstrap4 theme)  - with divs  (there is big space around it in card, it's complicated and this is not core plugin)

And with ul/li list there is problem with a tags (in my opinion it's bootstrap bug). 
Nevermind, fixed in e107 version

For reference to how this was fixed:
https://github.com/e107inc/bootstrap4/commit/b25be9d0ac35b0ef9fe9053e240a58b1c60c573c

Bootstrap4 detect if ul/li list is used in content and there switch card layout the correct way

```
			if($style === 'listgroup' && empty($options['list']))
			{
				$style = 'cardmenu';
			}

 
			if($style === 'cardmenu' && !empty($options['list']))
			{
				$style = 'listgroup';
			}
```

**Comment by SimSync** [comment]
@Jimmi08 Didn't i use a div to surround the a tags? I think it was no ul / li ...?!?

**Comment by Jimmi08** [comment]
@SimSync yes, but there is different template for bootstrap 4.  In theme folder.  You did everything fine.  It's specific problem for bootstrap4. With your template it looks like this:
![image](https://user-images.githubusercontent.com/5429548/60427317-bad08a80-9bf6-11e9-8d21-771708f8a38c.png)
So this needs to be fixed in theme.  
You have templating able menu and it's enough.

**Comment by SimSync** [comment]
From the BS4 docs:
![grafik](https://user-images.githubusercontent.com/7572616/60427509-1d298b00-9bf7-11e9-9a19-ff1c4bac2c3d.png)
For me it looks like, in my template it is only missing the "list-group-item-action" class on the `<a>` tag to make it work in BS4?

**Comment by Jimmi08** [comment]
Yes,
but you need to use this in card layout

https://getbootstrap.com/docs/4.0/components/list-group/
or
https://getbootstrap.com/docs/4.0/components/card/#list-groups

**Comment by SimSync** [comment]
See also this: https://getbootstrap.com/docs/4.0/components/list-group/#links-and-buttons
No need for `<ul><li><a>` or ? Maybe i did understand something completely wrong ...
I'll give it a deeper look once i'm home.

**Comment by Jimmi08** [comment]
@SimSync you are right for the solution without cards.  Look at cards.

**Comment by SimSync** [comment]
@Jimmi08 I've just commited a PR that includes an update to the template.
Unfortunatly, in BS3 i can't use `<ul><li><a>` for this purpose. I had to use `<div><a>`. It looks like, BS4 handles this completely different.
I included also the badge to display the number of products in that category. So it's worth to have a look...  😃

**Comment by Jimmi08** [comment]
Oh, bootstrap3 is ok, until admin theme will not be changed (in years, I suppose).  
That bt4 template is available and free, so anyone who wants bt4 version can use it. 

I will look at this. By the way, I really like your way with shortcodes - one shortcode with parameter what data to return and putting all HTML code to the template.

**Comment by SimSync** [comment]
Yes, thanks. 😄 I found it much more convenient to lookup just one shortcode, instead of searching the entire shortcode files for a shortcode, that returns some specific data. With my approach, you only have to look for a single shortcode and directly have an overview about what data this shortcode can return. Adding another key is simple and everything is still in one place.
