### ISSUE TITLE
Cannot checkout anymore

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/vstore#145]
When a order is placed, the last button does not work anymore gives a blanc screen, order does appeare in admin.. Nothing changed here only used the github of today (25-6-2019)

The last stage is this screen:
![vstore_nocheckout](https://user-images.githubusercontent.com/11962513/60100344-d6044b80-9759-11e9-90a9-27e28ab2987a.jpg)

Alex

**Comment by SimSync** [comment]
This is probably related to my last change. I'll check it tomorrow.

**Comment by SimSync** [comment]
@Alex-e107nl Should be fixed with latest PR. Please verify.

**Comment by Alex-e107nl** [comment]
Tested end it works again!
![vstore-succes](https://user-images.githubusercontent.com/11962513/60182013-bb96a480-9823-11e9-9911-b33651ab2bc8.jpg)

Thx Achim!
