### ISSUE TITLE
Clear cart only works when the link is /vstore/

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/vstore#148]
Just like the title says i cannot clear the cart when i am not on a /vstore/ link, it's a little confusing... :-)

Can someone test it also?

Alex

**Comment by SimSync** [comment]
@Alex-e107nl Was able to reproduce your issue and just implemented a fix. Please update from Github and test again.

**Comment by Alex-e107nl** [comment]
Yess it works now!!
Thx 

Alex
