### ISSUE TITLE
dashboard tabs update for bootstrap4

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/vstore#151]
This is fix:
- adding class="nav-item" to li tag
- adding class="nav-link"  to a tag

```
$active = ($this->var['area'] == $a ? 'class="nav-item active"': 'class="nav-item"') ;
$text .= '<li role="presentation" '.$active.'><a class="nav-link" href="'.e107::url('vstore', 'dashboard', array('dash' => $a)).'">'.$caption.'</a></li>
```

Problem is this:
$active = ($this->var['area'] == $a ? 'class="active"': '') ;

Active class is now with a tag, not with li. 
It's still work
 
![image](https://user-images.githubusercontent.com/5429548/60422712-d9318880-9bec-11e9-848d-072cbad81210.png)

but with the correct active class position, it looks like this:
![image](https://user-images.githubusercontent.com/5429548/60422719-dfc00000-9bec-11e9-8189-6f1dabe2dd1d.png)

No idea what is prefered solution (I would put the active class to both tags, but maybe switch for bootstrap4 is a better idea)

Thanks

**Comment by SimSync** [comment]
@Jimmi08 I'll have a look into it.

**Comment by SimSync** [comment]
@Jimmi08 Just commited a PR which should fix this issue also for BS4. Moved the hardcoded dashboard nav to the dashboard template file, so it can be styled as wanted.

**Comment by Jimmi08** [comment]
Do you put this to template? Wow.  Awesome. And perfect.   Thank you.
