### ISSUE TITLE
fatal error after manual confirmation via admin

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/vstore#156]
`Fatal error: Uncaught Error: Call to undefined method vstore::emailCustomerOnStatusChange() in C:\xampp\htdocs\xxx\e107_plugins\vstore\inc\admin_config_orders.php:242 Stack trace: #0 C:\xampp\htdocs\xxx\e107_handlers\admin_ui.php(4642): vstore_order_ui->afterUpdate(Array, Array, '1') #1 C:\xampp\htdocs\lugera20180615\e107_handlers\admin_ui.php(5974): e_admin_controller_ui->_manageSubmit('beforeUpdate', 'afterUpdate', 'onUpdateError', 'edit') #2 C:\xampp\htdocs\xxx\e107_handlers\admin_ui.php(2094): e_admin_ui->EditSubmitTrigger('update') #3 C:\xampp\htdocs\xxx\e107_handlers\admin_ui.php(1264): e_admin_controller->dispatchObserver() #4 C:\xampp\htdocs\xxx\e107_handlers\admin_ui.php(1074): e_admin_dispatcher->runObservers(true) #5 C:\xampp\htdocs\xxx\e107_plugins\vstore\admin_config.php(178): e_admin_dispatcher->__construct() #6 {main} thrown in C:\xampp\htdocs\xxx\e107_plugins\vstore\inc\admin_config_orders.php on line 242`

Order with bank transfer. Manual confirm processing. Then Order complete and this error appears.

Then I did it again with new order and everything was ok.  Maybe the difference was that I switched tabs before complete order.

**Comment by SimSync** [comment]
Looks like there is still a reference to the "old" email method. I'll check it.

**Comment by tgtje** [comment]
Any update on this error, basically through about 80% or more on LAN conversion, but due to this error ( window>admin/sales) ANY button for orders (process etc..) or Update will trigger it
php 7.3.5.

At present i do stop,as i can not see what happens behind this point Sorry..

**Comment by Jimmi08** [comment]
No, thanks

**Comment by tgtje** [comment]
Issue is resolved as of 26-02-2021
