### ISSUE TITLE
Email cc for order submitted not happening after latest update

### ISSUE THREAD

**Issue by martyshep** [e107inc/vstore#159]
My store is set so it cc's the originating email address so the guys who post out my goods know to send our an item. Now when a sale is made, only the purchaser gets the email, not the CC email address.

**Comment by CaMer0n** [comment]
@martyshep I believe this is fixed in the current version. (which requires the latest e107 git btw)

**Comment by realmontazeri** [comment]
@CaMer0n I enabled (CC to yourself) option in Vstore >> Email Templates and didn't receive any email.

**Comment by CaMer0n** [comment]
Thank you for the update. I will check on that.

**Comment by tgtje** [comment]
**Just info** in regards to CC > 
`
		$eml = array(
			'subject'      => $tp->lanVars($subject, varset($this->data['order_ref'])),
			'sender_email' => $sender_email,
			'sender_name'  => $sender_name,
			'html'         => true,
			'template'     => 'default',
			'body'         => $tp->parseTemplate($template, true, $this->sc)
		);`
		
		Might there be a conflict between HTML while e107 uses Text+Html ? Or reply-to like in mail manager class?

**Comment by CaMer0n** [comment]
@tgtje @martyshep @realmontazeri  I believe this commit should fix it. Please test again if you don't mind.

**Comment by tgtje** [comment]
Yes thank you @CaMer0n 👍   While i was running live mode with language (used this to test) run only on English, replacing those 3 files in question (ok some LAN's not present, but runs). Email setting all on ON.  I placed an order and voila 
Buy > received mail as client and also as admin.
Order completed > mail as client and as admin (trigger=update (ok) )
Refund > mail as client and as admin (trigger=update (ok) )
Canceled > mail as client and as admin (trigger=update (ok) ) (even an old one in list now did react on setting /cancel) 👍 

Grrr... files need LAN's ( and i thought i was done..hihi) back to design > pull r. closed .

**Comment by CaMer0n** [comment]
Thank you @tgtje !! I left some more comments for the LANs. (sorry, more work) 

When you test your purchases, are you using a paypal sandbox, or something else?

**Comment by tgtje** [comment]
I (since i do have no real gateway accounts (after your message i looked at paypal (sandbox) i might get a developer account..Have to read in.

On question : from the start i always used Bank transfer (that is way i kept away trying to change too much what might interfer with the gateway communication).
