### ISSUE TITLE
error on step5 gateway paypal

### ISSUE THREAD

**Issue by kreossino** [e107inc/vstore#16]
i have this error on vstore installed. i have inserted my api-paypal credential on admin_area, 
but the plugin not work correctly.

![vstore_error](https://cloud.githubusercontent.com/assets/11265955/16172393/30bf4eb2-3588-11e6-8959-f3b37650a555.jpg)

**Comment by CaMer0n** [comment]
Thank you @kreossino Indeed, this plugin is a work-in-progress at this time.

**Comment by kreossino** [comment]
I need to sort out and I'm not able with php ... for you to finish "first"  the part of the payment procedure is a problem?

**Comment by kreossino** [comment]
ok.. i have tested Paypal "sandbox"
in the step 6 erro in paypal the products it's not present 
after payed the product with paypal (creditcard or account) return correctly on website, but
in website the session not change "7"
and in admin_plugin_vstore is not present the customer buyer order.
![sandbox](https://cloud.githubusercontent.com/assets/11265955/16476120/6f150788-3e84-11e6-9937-c15aa5e6adc3.png)

**Comment by CaMer0n** [comment]
@kreossino Yes, I'm aware of this issue. I'm having trouble with the omnipay class as I haven't found enough good documentation about the paypal integration.

**Comment by CaMer0n** [comment]
Was recently fixed.
