### ISSUE TITLE
Cryptocurrency payment solution

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/vstore#166]
It would be nice to provide bitcoin/ethereum payment gateway with an independent wallet for vstore plugin.

**Comment by realmontazeri** [comment]
This decentralized API looks nice! https://github.com/bitcoinz-wallets
No signup is required and multi-currency support

**Comment by CaMer0n** [comment]
@realmontazeri Here are the payment gateways that vstore could easily support. (since it is using the omnipay package) 

https://omnipay.thephpleague.com/gateways/community/

**Comment by realmontazeri** [comment]
> @realmontazeri Here are the payment gateways that vstore could easily support. (since it is using the omnipay package)
> 
> https://omnipay.thephpleague.com/gateways/community/

But there are only Paypal, Mollie and bank transfer options, where can I find omnipay?
![Screenshot](https://user-images.githubusercontent.com/10089685/105113735-be7a7980-5ada-11eb-9edf-b1cc055d0e84.png)

**Comment by CaMer0n** [comment]
It's a library, not a payment gateway. You find the files here: ```e107_plugins/vstore/vendor/omnipay```
