### ISSUE TITLE
Products picture were disappeared after updating to the latest e107git

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/vstore#167]
I tried to upload new pictures but It is still the same problem.

**Comment by CaMer0n** [comment]
@realmontazeri On the frontend or the admin area?

**Comment by realmontazeri** [comment]
> @realmontazeri On the frontend or the admin area?

Frontend (pictures in admin area are ok)

**Comment by CaMer0n** [comment]
Thanks @realmontazeri It should be fixed now.
