### ISSUE TITLE
Site blank page on the latest vstore git version

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/vstore#168]
Blank page happened on website frontpage and also vstore admin dashboard (e107 backend is ok)

**Comment by Moc** [comment]
Please always share your PHP version with these type of issues

**Comment by realmontazeri** [comment]
This issue was happened on the latest e107git version and php v7.4

**Comment by Moc** [comment]
@CaMer0n Pretty sure this is caused by the vendor folders update. What I did to fix it:
- Delete composer.lock file
- Delete vendor folder
- Run 'composer install'

The error for me was:
```
PHP Fatal error:  require(): Failed opening required 'C:\webdev\www\clean2706\e107_plugins\vstore\vendor\composer/../clue/stream-filter/src/functions_include.php' (include_path='.;C:/webdev/etc/php/pear') in C:\webdev\www\clean2706\e107_plugins\vstore\vendor\composer\autoload_real.php on line 71
```

**Comment by realmontazeri** [comment]
The issue no longer exists after I updated my website to the latest vstore git version today.
