### ISSUE TITLE
Payment gateways fatal error

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/vstore#169]
The following error appears when I click on payment gateways in vstore admin area:

Fatal error: Uncaught Error: Cannot pass parameter 1 by reference in /home/.../plugins/vstore/vstore.class.php:485 Stack trace: #0 /home/.../plugins/vstore/inc/admin_config_gateways.php(82): vstore::getMolliePaymentMethodIcon('mollie_banconta...', '2x') #1 /home/.../handlers/admin_ui.php(1474): vstore_gateways_ui->init() #2 /home/clients/.../handlers/admin_ui.php(1447): e_admin_dispatcher->_initController() #3 /home/.../handlers/admin_ui.php(1333): e_admin_dispatcher->getController() #4 /home/clients/.../handlers/admin_ui.php(1105): e_admin_dispatcher->runObservers() #5 /home/.../plugins/vstore/admin_config.php(178): e_admin_dispatcher->__construct() #6 {main} thrown in /home/.../plugins/vstore/vstore.class.php on line 485

**Comment by realmontazeri** [comment]
This issue was happened in the latest e107git version with php v7.4

**Comment by realmontazeri** [comment]
@CaMer0n I appreciate for any solutions related to this because I really don't want to migrate to another shopping cart system.

**Comment by Moc** [comment]
Please be a little more patient. This issue will be looked into asap.

**Comment by Moc** [comment]
Fixed in https://github.com/e107inc/vstore/commit/4ce3162163f2ffe5dddcf323398e72115b16f9c7
