### ISSUE TITLE
Vstore statistics miscalculation

### ISSUE THREAD

**Issue by 2548ir** [e107inc/vstore#170]
Both orders are cancelled but they are still appear as open orders, also there are no any records to show after I click on open orders.
![Screenshot](https://user-images.githubusercontent.com/10089685/103442877-186fe800-4c6f-11eb-9c21-7da38a1484be.png)

**Comment by realmontazeri** [comment]
@CaMer0n This issue is back again

**Comment by CaMer0n** [comment]
Thanks @realmontazeri . Are they cancelled orders or something else?

**Comment by realmontazeri** [comment]
> Thanks @realmontazeri . Are they cancelled orders or something else?

Complete, Incomplete, Refunded (It shows 2 open orders)

**Comment by CaMer0n** [comment]
okay, thank you.

**Comment by realmontazeri** [comment]
> okay, thank you.

You're welcome! btw, when I click on open orders then it goes to sales page with no records but if I click on sales directly from the main menu then It goes to sales page with those available records.

**Comment by 2548ir** [comment]
This issue has been fixed with the latest changes.
