### ISSUE TITLE
Cart navigation link drop down window was disappeared

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/vstore#171]
Today after updating to the latest e107git version I found out that the cart navigation link drop down window was disappeared:
![Screenshot](https://user-images.githubusercontent.com/10089685/104128702-61feb800-537e-11eb-8bf0-726f1549ba79.png)

**Comment by realmontazeri** [comment]
Also the following error was appeared on checking out after adding some products to cart:
![Screenshot](https://user-images.githubusercontent.com/10089685/104737441-7d403d80-5759-11eb-8c87-342a7b521299.png)

**Comment by realmontazeri** [comment]
Fresh installation results:
![screenshot1](https://user-images.githubusercontent.com/10089685/104840061-50676400-58da-11eb-8023-bcecf8709639.png)
![screenshot2](https://user-images.githubusercontent.com/10089685/104840064-52c9be00-58da-11eb-8f76-32553e35df7c.png)

**Comment by CaMer0n** [comment]
This is a core issue with navigation, as the plugin has barely had any modifications recently. 

Please sync with the github version. 

## My Local Tests: 

![image](https://user-images.githubusercontent.com/2825679/104872899-fa0f1b00-5903-11eb-84f5-f2166c87f185.png)

![image](https://user-images.githubusercontent.com/2825679/104872950-2034bb00-5904-11eb-8836-8af834eb4718.png)

I have also added unit tests to check for the navigation issue.

**Comment by realmontazeri** [comment]
Thank You @CaMer0n
