### ISSUE TITLE
Graph or chart feature

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/vstore#174]
It is very useful to have this option in administration dashboard.

**Comment by CaMer0n** [comment]
There is already a chart, but I have added 2 others and cleaned it up a bit. 

![screenshot-localhost-2021 01 28-09_30_46](https://user-images.githubusercontent.com/2825679/106176679-78fa2400-614c-11eb-9858-f0d7a15d7a97.png)

**Comment by realmontazeri** [comment]
@CaMer0n Thank you, the new interface looks amazing!
