### ISSUE TITLE
Letter is not acceptable for product code

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/vstore#177]
It was ok before but currently only digits are acceptable and I don't know if those duplicated astrix are related or not.

![Screenshot](https://user-images.githubusercontent.com/10089685/109348184-709b2300-7889-11eb-8852-b8778d8406ab.png)

**Comment by CaMer0n** [comment]
What if you use UPPERCASE?

**Comment by realmontazeri** [comment]
> What if you use UPPERCASE?

Uppercase does work except for lowercase and signs like dash
