### ISSUE TITLE
Cancel order 

### ISSUE THREAD

**Issue by tgtje** [e107inc/vstore#178]
Description : re-tested system > problem found.

After placing an order and i would (using customer panel) want to revolke (cancel) my order getting the following error : 

`Fatal error: Uncaught Error: Call to undefined method vstore::emailCustomerOnStatusChange() in R:\Xamp801\htdocs\vstore\e107_plugins\vstore\vstore.class.php:742 Stack trace: #0 R:\Xamp801\htdocs\vstore\e107_plugins\vstore\vstore.class.php(288): vstore->process() #1 R:\Xamp801\htdocs\vstore\e107_plugins\vstore\vstore.php(41): vstore->init() #2 R:\Xamp801\htdocs\vstore\index.php(69): include_once('R:\\Xamp801\\htdo...') #3 {main} thrown in R:\Xamp801\htdocs\vstore\e107_plugins\vstore\vstore.class.php on line 742`.
Likely this is a piece (not addressed/unaware) that also refers to the recent changes on inc/admin config orders in regards to not sending out emails/blank page error #156  (> line 250 and 260 were changed and work).

**Comment by CaMer0n** [comment]
@tgtje Thanks. Yes, it's the same kind of error. (calling the method from the wrong class) .

**Comment by CaMer0n** [comment]
@tgtje Please try again. Thank you.

**Comment by tgtje** [comment]
@CaMer0n Thank you , now working. (although customer now shows cancelled, no mail is send;  but admin has it displayed cancelled also;  helas iff i have to inform customer i need to process and cancel als admin, to send email.
