### ISSUE TITLE
Not able to make a new root-category.

### ISSUE THREAD

**Issue by Norwayman** [e107inc/vstore#18]
When I write TEST in the title and ROOT as parent, the title is not saved.
 And also there is no SEF generated.

**Comment by Norwayman** [comment]
@CaMer0n 
Update as of July 4:  When I now create a new category it generates the SEF,
but it still not saves the title-field.

**Comment by CaMer0n** [comment]
@Norwayman Please update the e107 core and then this plugin.

**Comment by Norwayman** [comment]
@CaMer0n Yes, now it works perfect! Thanks a lot!
