### ISSUE TITLE
FA BANK

### ISSUE THREAD

**Issue by tgtje** [e107inc/vstore#182]
Just to be sure, does the fa-bank glyph (inc/adm.conf.gatew. ) and  or icon fa-bank (vstore.class) be renamed and which or both ?
Internal the image is present, but not  on front eg is >  fa fa-bank preferable? depending on the used fontawesome build in running system versions?

**Comment by CaMer0n** [comment]
fa-bank should work with FontAwesome4 and FontAwesome5 since it is passed thru toGlyph() or toIcon().   So, there's nothing to rename there as far as I know.

**Comment by tgtje** [comment]
Can't find a real 'glitch' that is does not work, In an earlier version it did. (maybe related to somethingin the lang tests?) 
 Of course i can replace the icon, that works anyway. Thank you.

**Comment by CaMer0n** [comment]
@tgtje Which theme are you using?

**Comment by tgtje** [comment]
Info/reminder : been testing the newer pieces, the fa bank is not displayed in Voux, it does work in BS3.
If it concerns.. BS3 overall has nicer view on front than Voux (probably the styling/css), especially the cart (select) window (pop out) eg. placeholder for cust panel, checkout, empty (large and black bg for checkout..(ehh ugly)).

**Comment by tgtje** [comment]
Just as comment : maybe the issue kies here too git issue : https://github.com/e107inc/e107/issues/4471 .(+commit)
I do need to test it though.

**Comment by tgtje** [comment]
Before install of latest Gitversion : Theme Voux
![before](https://user-images.githubusercontent.com/1811857/114267344-37fb7700-99fb-11eb-8ebc-af9cc67de3cf.jpg)
After update IWTH latest Gitversion (incl. commit) Theme Voux.

![after](https://user-images.githubusercontent.com/1811857/114267369-6c6f3300-99fb-11eb-833b-188e7457b9a5.jpg)

Concluding : commit solves issue.

**Comment by CaMer0n** [comment]
Great! Thank you @tgtje !
