### ISSUE TITLE
Delimiter

### ISSUE THREAD

**Issue by tgtje** [e107inc/vstore#183]
While testing for errors:
a)
Warning preg_match(): No ending delimiter '^' found, Line 424 of R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\vstore.class.php.

solved with : `		if(preg_match('^[0-9.]+x$/', $size))`  added the / correct?

b) using PDF > ON to use
checkout page ( the one supposes to display for me as customer that order is created and email send.. eg bill form

Fatal error: Array and string offset access syntax with curly braces is no longer supported in R:\Xampp-8.0.3\htdocs\newest\e107_plugins\pdf\tcpdf.php on line 16893

Github version (latest today 03/25/21)
Inc : Vstore (main)
Inc: PDF
Xampp local php 8.0.3 
All fresh installs, only English.

**Comment by CaMer0n** [comment]
@tgtje Thank you. That regex does need a fix. 
I'm not a big supporter of the pdf plugin. (or this feature)

**Comment by tgtje** [comment]
Changed the title to delimiter only as pdf had an update to a working solution (afaics).

**Comment by CaMer0n** [comment]
@tgtje Thanks Leo. This last commit should fix it.

**Comment by tgtje** [comment]
Tested local and live (8.0.3 vs live 7.4.10) does not report any errors and all seems to work.
Close?
