### ISSUE TITLE
Guest sale

### ISSUE THREAD

**Issue by tgtje** [e107inc/vstore#184]
Bug, error, or needs adjusting idea ?

functionabilty :
can not find how to :
When customer is Guest (no membership) and would be allowed to order.

Using checkout php 8.0.3 throws error on USERNAME  (coded on line 498 inc/vstore_order_class
A guest has **no**  username> as undefined constant USERNAME and as such log is not filled > no issues when logged in.
Maybe something when guest displaying First/Lastname?? 

Fatal error: Uncaught Error: Undefined constant "USERNAME" in R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\inc\vstore_order.class.php:498 Stack trace: #0 R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\inc\vstore_order.class.php(580): vstore_order->setOrderLog('Invoice-Nr. ass...') #1 R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\vstore.class.php(1989): vstore_order->setInvoiceNr() #2 R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\vstore.class.php(1774): vstore->saveTransaction(NULL, NULL, Array) #3 R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\vstore.class.php(684): vstore->processGateway() #4 R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\vstore.class.php(290): vstore->process() #5 R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\vstore.php(41): vstore->init() #6 R:\Xampp-8.0.3\htdocs\newest\index.php(69): include_once('R:\\Xampp-8.0.3\\ht...') #7 {main} thrown in R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\inc\vstore_order.class.php on line 498

Github version (latest 03/25/21)
Inc : Vstore (main)
Inc: PDF
Xampp local php 8.0.3
All fresh installs, only English.

**Comment by CaMer0n** [comment]
@tgtje Thank you! If you don't mind, please test again with the changes.

**Comment by tgtje** [comment]
Same installment (nothing changed besides pdf).
Helas..
Fatal error: Uncaught Error: varset(): Argument #1 ($val) cannot be passed by reference in R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\inc\vstore_order.class.php:497 Stack trace: #0 R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\inc\vstore_order.class.php(580): vstore_order->setOrderLog('Invoice-Nr. ass...') #1 R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\vstore.class.php(1989): vstore_order->setInvoiceNr() #2 R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\vstore.class.php(1774): vstore->saveTransaction(NULL, NULL, Array) #3 R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\vstore.class.php(684): vstore->processGateway() #4 R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\vstore.class.php(290): vstore->process() #5 R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\vstore.php(41): vstore->init() #6 R:\Xampp-8.0.3\htdocs\newest\index.php(69): include_once('R:\\Xampp-8.0.3\\ht...') #7 {main} thrown in R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\inc\vstore_order.class.php on line 497

**Comment by tgtje** [comment]
Nothing chnaged besides pdf plugin.
Same installment : Helas

Fatal error: Uncaught Error: varset(): Argument #1 ($val) cannot be passed by reference in R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\inc\vstore_order.class.php:497 Stack trace: #0 R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\inc\vstore_order.class.php(580): vstore_order->setOrderLog('Invoice-Nr. ass...') #1 R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\vstore.class.php(1989): vstore_order->setInvoiceNr() #2 R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\vstore.class.php(1774): vstore->saveTransaction(NULL, NULL, Array) #3 R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\vstore.class.php(684): vstore->processGateway() #4 R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\vstore.class.php(290): vstore->process() #5 R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\vstore.php(41): vstore->init() #6 R:\Xampp-8.0.3\htdocs\newest\index.php(69): include_once('R:\\Xampp-8.0.3\\ht...') #7 {main} thrown in R:\Xampp-8.0.3\htdocs\newest\e107_plugins\vstore\inc\vstore_order.class.php on line 497

**Comment by CaMer0n** [comment]
@tgtje Sorry, this commit "should" work. Please try again.

**Comment by tgtje** [comment]
Thank you, success.

tested twice : when with varset error arises.
The new commit with defset works 
(note : only tested on Bank Transfer as no other payment channels are set).
Here's an example of the logs :

![logs](https://user-images.githubusercontent.com/1811857/112972049-20490680-9150-11eb-92ce-fcaae4e8ace4.jpg)

**Comment by CaMer0n** [comment]
@tgtje Great! Thank you!
