### ISSUE TITLE
fresh install (coupon)

### ISSUE THREAD

**Issue by tgtje** [e107inc/vstore#192]
Noticed on previous installments..now fresh 
Using **Coupon code** eg make a new one.
Version 2.3.3 git, xampp local php 8.1.6 fresh out of the box (for testing) as 8.0.5 already had same issue.
(new xampp, new e107; latest vstore, NO translation in use > all original)

Fatal error: Uncaught TypeError: implode(): Argument #1 ($pieces) must be of type array, string given in localpath…..\e107\e107_plugins\vstore\inc\admin_config_coupons.php:78 Stack trace: #0 localpath…..\e107\e107_plugins\vstore\inc\admin_config_coupons.php(78): implode(',', NULL) #1 localpath…..\e107\e107_handlers\admin_ui.php(4960): vstore_coupons_ui->beforeCreate(Array, Array, 0) #2 localpath…..\e107\e107_handlers\admin_ui.php(6641): e_admin_controller_ui->_manageSubmit('beforeCreate', 'afterCreate', 'onCreateError') #3 localpath…..\e107\e107_handlers\admin_ui.php(2252): e_admin_ui->CreateSubmitTrigger('create') #4 localpath…..\e107\e107_handlers\admin_ui.php(1348): e_admin_controller->dispatchObserver() #5 localpath…..\e107\e107_handlers\admin_ui.php(1109): e_admin_dispatcher->runObservers() #6 localpath…..\e107\e107_plugins\vstore\admin_config.php(170): e_admin_dispatcher->__construct() #7 {main} thrown in localpath…..\e107\e107_plugins\vstore\inc\admin_config_coupons.php on line 78.

Identical for 2.3.2 on 8.0.5 and 2.3.3 8.1.6 ( $pieces related to Vendor??? as they have changed X2 last year)

(been a long time not realy active (personal things..) just taking up some open things...
As for translation goes : recompiling to new LAN define use with { ... }  not 100% in some files 15 work and 2 don't ( no errors).
But that is for later.....

**Comment by tgtje** [comment]
Update : again a long time passed, starting again/follow up, same bug appears but is seems most likely a result of php 8 
Needed functioning: min php 7 install v 2.3.2 (relationship new lan method) 8 will be crippled . Further changes on hold.

**Comment by tgtje** [comment]
Fix itself has result, but still investigating why coupon (operational in admin) will not display on everything related to ordering.
Dbase has tables, short : not displaying (like theres no 'table/div etc..)  neither BS5 nor BS3 (core themes).

**Comment by tgtje** [comment]
@Moc  although issue for coupon code, it is of a different nature. (if a relation ship consists i can not tell).
I 'found' a solution for this (latest) one, and created a commit.

The first post was solved using the provided fix.

**Comment by tgtje** [comment]
created commit

**Comment by CaMer0n** [comment]
@tgtje So your commit fixes this issue as well, correct?

**Comment by tgtje** [comment]
@CaMer0n your first commit fixed, the not being able to add a coupon (admin).
the 2 commits from me did change 1) the  display on front for the coupon 'line' (=image), be deleting a ending 'cart' (looked like a typo/leftover?? ) > vstore shortcode.
2) Since vstore also has a menu called by ITEM_PRICE it would display a zero price (€ or $ 0,00) where a item price should be.
Changing ITEM_PRICE to CART_PRICE fixed this.. (vs..template).
If you agree i close this one.
Thank you.

#198 remains.
