### ISSUE TITLE
Price issue on dropdown

### ISSUE THREAD

**Issue by tgtje** [e107inc/vstore#198]
Drop down panel (cart)

When change amount of items to buy ( ex 1 item > 3 items..), the top bar number increments to correct amount, assuming item count.
However the price next to item itself increments in number but _amount totals_.

would better >  reflect amount  (ex..  3 x PER item  >  3 x €50) since SUBtotal (listed below)  already calculates the total item amount price..
(can not find what to change to alter this...)
![storecart](https://user-images.githubusercontent.com/1811857/203092604-07b50f2c-76bb-4174-9283-896eb2c08193.jpg)

**Comment by CaMer0n** [comment]
Thanks @tgtje This commit should fix it.
