### ISSUE TITLE
Strange category layout

### ISSUE THREAD

**Issue by Norwayman** [e107inc/vstore#2]
Firts of all:  great initiative with the online store! :)

I tried making 9 different categories and it gives me a strange layout
when displaying them. It is like the thumbs are not filling out the rows.
Here is a screen shot:

![vstorecategories](https://cloud.githubusercontent.com/assets/1757346/14938245/23b262fc-0ee3-11e6-9a53-e8be5fe542f6.JPG)

What would be the explanation for this?

**Comment by CaMer0n** [comment]
Thanks @Norwayman This is a bootstrap css issue. I'll fix it in the core.

**Comment by Norwayman** [comment]
Thanks this fixed it.
it now shows 9 categories nicely 3 by 3 on the page,
but....I have 13 categories. How to display them all?

**Comment by CaMer0n** [comment]
@Norwayman It's not displaying more than 9 categories?

**Comment by Norwayman** [comment]
NO, it is just displaying 9 categories out of the 13 I have made.

**Comment by CaMer0n** [comment]
@Norwayman And all of them are set to visible by everyone?

**Comment by Norwayman** [comment]
@CaMer0n Yes....all are set to visible to everyone.
I noticed however that if I do not set a SEF url then one cannot click on a category
and get further info. Once I manually set the SEF url I could get info on the products under a category.
Don't know if that has anything to do with the issue of not being able to se all 13 categories.

**Comment by CaMer0n** [comment]
@Norwayman Please try now.

**Comment by Norwayman** [comment]
Yes! Now I can display all my categories like this:

![vstorecategories03](https://cloud.githubusercontent.com/assets/1757346/15099328/f4a59e4e-1517-11e6-9982-bfcb49576056.JPG)

But....can't I display all categories on ONE page only?
Could there be adjustments in settings that let the admin
decide how many will be displayed per page?

See I have a lot of space to fill out here:

![vstorecategories02](https://cloud.githubusercontent.com/assets/1757346/15099335/21dec322-1518-11e6-9fbc-e884ea11224d.JPG)
