### ISSUE TITLE
[Help Request] Zoom issue on image 2, 4, 6 on iPhone

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/vstore#21]
I have added the image zoom feature which works well on the iphone for the first, third and 5th image on the product page. But the 2nd, 4th and 6th image has an issue and does not magnify/switch correctly. 
Any suggestions/fixes would be appreciated. @lonalore @Jimmi08 

In the following example, the images with this problem are '1' , '3', '5'

![screenshot-localhost-2016-10-21-15-09-45](https://cloud.githubusercontent.com/assets/2825679/19613286/833a3146-97a0-11e6-95c5-8640c4136c98.png)

**Comment by lonalore** [comment]
Okay, I'll check it today.

FYI: I installed it on my website, and I cannot add product to a category, because it does not save category to the product.

**Comment by lonalore** [comment]
I had the same issue on my Android phone. This commit should fix both! Could I create a pull request?

**Comment by CaMer0n** [comment]
@lonalore The issue still remains (using desktop / Firefox) that the 'zoom' shows the previous image, not the one that was just clicked.

**Comment by CaMer0n** [comment]
👍
