### ISSUE TITLE
error in item_inventory method

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/vstore#25]
There is mistypo in item_inventory function (I can't send request because I am working on other things)
```
// Custom Method/Function
function item_inventory($curVal,$mode)
{
	$frm = e107::getForm();
	switch($mode)
	{
		case 'read': // List Page
			return $curVal;
		break;
		case 'write': // Edit Page
			return $frm->number('item_cat',$curVal);
		break;
```

![image](https://cloud.githubusercontent.com/assets/5429548/20214452/9ac78ae2-a80e-11e6-97dd-91d33e262a68.png)

**Comment by CaMer0n** [comment]
Thank you!! 👍
