### ISSUE TITLE
REQUEST: Sub categories?

### ISSUE THREAD

**Issue by Norwayman** [e107inc/vstore#3]
PLEASE: Would it be possible to add sub-categories? That would be awesome! :)

**Comment by CaMer0n** [comment]
@Norwayman Please give it a try. Breadcrumb still needs work.

**Comment by Norwayman** [comment]
@CaMer0n Yes, this worked very well. Now, is there a change one could rearrange the order of the categories, like in site links for example?

**Comment by CaMer0n** [comment]
@Norwayman I believe the drag-n-drop sorting is working too now. Same for you?

**Comment by Norwayman** [comment]
@CaMer0n Yes, I think it does. Last time I checked anyway. I will let you know if they do not work :)
