### ISSUE TITLE
New feature: Coupon codes

### ISSUE THREAD

**Issue by SimSync** [e107inc/vstore#53]
- [x] Coupon codes reduce item price by a fixed or a percentage amount (e.g. -5€ or -15%)
- [x] Coupon codes may be used on individual items or categories, or items/categries may be excluded
- [x] Coupon codes may be valid for a limited time only
- [x] Coupon codes may be used only in limited numbers in general and/or by customer or per item quantity

**Comment by SimSync** [comment]
Feature implemented, but as all features of this plugin needs testing!

**Comment by CaMer0n** [comment]
:+1:
