### ISSUE TITLE
add paypal's royalties for service costs

### ISSUE THREAD

**Issue by kreossino** [e107inc/vstore#54]
hi, if is possible  could you add a field for extra costs of paypal?

**Comment by SimSync** [comment]
This topic can get quite complex, even if you limit it to Paypal.
The fixed amount depends on the currency, the percentage depends on your organization form and also the way your customers pay and so on.
Wouldn't it make sense to calculate that cost into your product price and not to charge your customer for the selected payment method?

**Comment by kreossino** [comment]
if the customer pay the product with bank trasnfer this have a fixed cost, but with paypal this is in percentage

**Comment by Moc** [comment]
This is not allowed based on several laws and regulations. You'll have to incorporate it into your sales price.
