### ISSUE TITLE
bug email

### ISSUE THREAD

**Issue by kreossino** [e107inc/vstore#56]
if i complete a order i receive only this message. "array"

<img width="866" alt="schermata 2018-03-14 alle 08 22 33" src="https://user-images.githubusercontent.com/11265955/37409241-beda1ae6-2795-11e8-8daa-22f01bec5ec3.png">

**Comment by SimSync** [comment]
Fixed the issue in my fork. Will be included in my next pull request.

**Comment by SimSync** [comment]
@kreossino The fix is now implemented. Could you please check and verify?

**Comment by kreossino** [comment]
perfect !

**Comment by kreossino** [comment]
@SimSync  
when the customer buys my products, he receives a confirmation e-mail.
can I receive it too?
