### ISSUE TITLE
REQUEST: Option of selecting size?

### ISSUE THREAD

**Issue by Norwayman** [e107inc/vstore#6]
Could there be an option for selecting clothing size?

![vstoreoptionforsize](https://cloud.githubusercontent.com/assets/1757346/15059594/34f7c46c-12e9-11e6-81ed-70e49ba22891.JPG)

**Comment by Moc** [comment]
Maybe something more generic like  'attributes' could work

For example 'sizes' for clothing and shoes but also 'color' or 'model type' etc.

**Comment by Norwayman** [comment]
Yes, sounds like a good idea :)

**Comment by martyshep** [comment]
Product properties array such as size so needed thanks :)

**Comment by CaMer0n** [comment]
@Norwayman @martyshep @Moc Admin area for this is mostly complete. Frontend stuff still needs to be added.
