### ISSUE TITLE
new feature: field on order

### ISSUE THREAD

**Issue by kreossino** [e107inc/vstore#60]
Hi, 
could you add three fields on order form?
that's for:
1)  fiscal code; (codice fiscale)
2) VAT - (Partita Iva)
3) factory (nome azienda)
and the captcha code to confirm

**Comment by SimSync** [comment]
You mean on the order confirmation page or which page exactly?
Isn't this something that should be located in the imprint or on the invoice?
Do you have an example of it (screenshot or similar)?

**Comment by kreossino** [comment]
you could add a field 
"VAT" and the  personal fiscal code with verify  (html5)
`<input type="text" id="iscritti_codicefiscale" pattern="^[a-zA-Z]{6}[0-9]{2}[a-zA-Z][0-9]{2}[a-zA-Z][0-9]{3}[a-zA-Z]$" >` (not required)

and in the next step for confirm order a "recaptcha code" 

![form](https://user-images.githubusercontent.com/11265955/37642992-0e7eb37e-2c17-11e8-97c2-bcc13d4cba24.png)

**Comment by Jimmi08** [comment]
@SimSync for your explanation (If I understand above correctly):

- **fiscal code** -  it's identification number for any taxable company (something like registration number) . The label should be easy changed - (we use ICO for this)  (I saw this solved with next line in adress without label after company name), label was just a placeholder.  Without this code invoices are not acceptable by our tax authorities. 

- **VAT number** - it's only for EU countries (if your company have it, your vat tax should be zero and you need to add special text to invoice).  If EU company doesn't have it, and it's digital product, you should use tax percent from company country not from your country. 
Not mention that you should verified inserted VAT number...  

By the way, great work with other things.

**Comment by SimSync** [comment]
Ah OK. You're talking about the data from the customer, not your merchant data.
Well, as written here #63 , i think we need an invoice address and your fields should be included there as it is information about the one who pays the bill and not who receives the items.
So once, invoice address gets implemented i'll keep an eye on this.

**Comment by Jimmi08** [comment]
@SimSync let this confirm by @kreossino  It was just my quess.

**Comment by SimSync** [comment]
At least on my todo list, this isn't a top priority. So he has time to confirm ... 😄 
I think, first storing the recurring customer data for later reference is something that needs to be done before requesting any additional data from the customer.

And by the way: @kreossino You can have the fields already today, by defining the additional checkout fields in the preferences.  😆

**Comment by kreossino** [comment]
@Jimmi08 @SimSync 

the VAT is writted from customer in this form only he buy this merchandise for the company.

the fiscal code is for the identification of customer in Italy this code is a personal data unique code. 
the customer must indicate this for receive the marchandise.

i must use the "additional checkout fields" ... 👍

**Comment by Jimmi08** [comment]
@SimSync See? It depends on country law.  So Additional checkout fieds is correct way.  

@kreossino Just from curiosity and maybe wrong translation.  Really "personal"  like not freelancer,  not company but normal person? I am looking for how you do this with GDPR.  We have this "code" too, but it's the most warded information and if you are asking it from people, you can get to serious troubles.

**Comment by kreossino** [comment]
@Jimmi08 yes in Italy the fiscal code is necessary for all person and freelances and with a VAT "Partita Iva" for company ( we use this fiscal code for buy medicine, Hospital, documents, shipping merchandise and all other!)

**Comment by kreossino** [comment]
![form1](https://user-images.githubusercontent.com/11265955/37646899-ce7ccee4-2c22-11e8-8747-d8c931465aac.png)

**Comment by SimSync** [comment]
I already expect when i wrote about the additional fields that this would come ... 😆 
(in future) Maybe this can be solved by modifying the template. At the moment, additional fields are fixed to be rendered after the main fields. I'll open an issue for it to not forget about it.

But I still think, that this should be included (as optional field) into the invoice address. And to position it by modifying the template (if the default position (at the end) doesn't suit).

**Comment by SimSync** [comment]
There is a webservice of the EU to verify the VAT number: http://ec.europa.eu/taxation_customs/vies/vatRequest.html
I found this package on gitgub: https://github.com/DragonBe/vies
There are also others. Don't know which is best. But at least there is already something to validate the VAT number.

**Comment by Moc** [comment]
Tax / VAT Code: #69 

-----------
> I already expect when i wrote about the additional fields that this would come ... laughing
(in future) Maybe this can be solved by modifying the template. At the moment, additional fields are fixed to be rendered after the main fields. I'll open an issue for it to not forget about it.

What about this? @SimSync

**Comment by SimSync** [comment]
Yes, the fields are defined as shortcodes which can be placed as you like in the template.

**Comment by SimSync** [comment]
But the vat and tax code fields are "fixed" fields that will be rendered on billing address page and not on the shipping address page. The shipping address is now optional.
