### ISSUE TITLE
new feature: Invoice (Email & PDF)

### ISSUE THREAD

**Issue by SimSync** [e107inc/vstore#61]
I think, we need a "real" invoice for the purchases. As a simple email, but also as pdf.
Layout should be editable via the preferences.
The invoice should be send automatically when reaching a certain order status (e.g. completed) or manually (button on the order table or so).

**Comment by kreossino** [comment]
is only a idea 👍 
https://stackoverflow.com/questions/22727622/how-to-send-form-data-in-pdf-and-mail-after-submit
