### ISSUE TITLE
new feature: Invoice address

### ISSUE THREAD

**Issue by SimSync** [e107inc/vstore#63]
As the one who pays for a purchase and the one who receives it are not necessarily the same, we need an option to enter both.
Maybe first ask for the invoice address, than in the next step ask for the shipping address.
The customer can now decide if invoice- and shipping address are the same and in that case the step will be skipped and the customer will be directed directly to the summary/order confirmation page.

**Comment by CaMer0n** [comment]
Good idea! Yeah, Billing Address and Shipping address. (with a checkbox to use Shipping address as the Billing address) or simply a hidden form with "use a different address for billing" link.
