### ISSUE TITLE
sales status changed - bug

### ISSUE THREAD

**Issue by kreossino** [e107inc/vstore#79]
when you change the status (Processed ..Completed ) in sales area the Total is moltiplied and it add two 00, for example the order is 15,00 euros ... you change and update the "sales status" ...the Total now is 1500,00 ...you change another time? the Total now is 150000,00 ..  

<img width="1540" alt="bug_update order status" src="https://user-images.githubusercontent.com/11265955/39455424-d622a8c6-4ccf-11e8-8d5a-660a87ed64d2.png">

**Comment by SimSync** [comment]
@kreossino Now I know a bit more where to look. I'll check this.

**Comment by SimSync** [comment]
This seams only to happen when your website is set to italian. Maybe this is a Multilan issue? @CaMer0n

**Comment by SimSync** [comment]
i've updated my fork with a possible fix. could you please test?

**Comment by kreossino** [comment]
not resolved when i select "Completed" add two 0 at the Total
could you test directly?

**Comment by SimSync** [comment]
Yes, I understand. It's as if the . is replaced by nothing.
Did you switch to my fork and update to the latest version? My changes are not included in the official version.

**Comment by kreossino** [comment]
i dont know how make it

**Comment by SimSync** [comment]
@cameron Is this something you ever experienced? A value, that is readonly, is updated and malformed (30.00 becomes 3000) during save? This value isn't touched in beforeUpdate(). This happens only when Italian (or probably all languages except English) is set in a Multilan environment. With English is everything fine. Haven't tested till now what happens if the system language is set to a none English value (without Multilan).

**Comment by SimSync** [comment]
Just tested it. It happens too, if i set the system language to dutch ...

**Comment by SimSync** [comment]
This looks like a bug in e_model->toNumber() ...

**Comment by kreossino** [comment]
how can we resolve?

**Comment by SimSync** [comment]
This must be done in the e107 core.
I'll open an issue and see if i find a solution.

**Comment by SimSync** [comment]
Issue created and also a PR e107inc/e107#3114 with a possible fix.

**Comment by kreossino** [comment]
I hope it resolves
