### ISSUE TITLE
Category pages error

### ISSUE THREAD

**Issue by Norwayman** [e107inc/vstore#8]
@CaMer0n As you can see of my screen shot I have 3 pages of categories totaling 19 categories.
My problem is that when I go to page 2 of categories and click on IMANES (which contains two products to buy and is in stock) it does not go to see those two products, but goes back to page 1 of categories. How can I deal with this?

![secondpageofcategories](https://cloud.githubusercontent.com/assets/1757346/15377987/66782c34-1d25-11e6-8fe9-d740bc3cf2b7.JPG)

**Comment by CaMer0n** [comment]
Sounds like an issue with the SEF URL, I'll look into it.
