### ISSUE TITLE
link to invoice pdf 

### ISSUE THREAD

**Issue by kreossino** [e107inc/vstore#80]
the link of invoice is 
https://yourwebsite.com/vstore/invoice/8/

but this is correctly registered in e107_media/xxxxxx/plugins/vstore/user_x/xx

**Comment by SimSync** [comment]
@kreossino I'm not sure if I understand it correctly. Is this a question, a bug or just a statement?

**Comment by kreossino** [comment]
the link not open the invoice pdf "it don't rewrite" because the link not open the e107_media area where is the file ....{e107_media}...invoice.pdf

**Comment by SimSync** [comment]
does the user have rights to create folders/files under the e107_media folder?

**Comment by SimSync** [comment]
@kreossino Added a admin log message in case a folder couldn't be created (the folder for the invoice).
Please test...

**Comment by kreossino** [comment]
the system is ok but the files can't writed in the correct directories.
not in 
e107_media/0686beafb3/plugins/vstore/user00001/ ..fileinvoice.pdf
 it create a directory "user00001 ... user00002 ecc"
 but memorize the files in root directory not in user directory
e107_media/0686beafb3/plugins/vstore/ ..fileinvoice.pdf

and the link for view the invoice 
https://.../vstore/invoice/1/ 
is not correct because the invoice is in 
../e107_media/e107_media/0686beafb3/plugins/vstore/ ...fileinvoice.pdf

**Comment by SimSync** [comment]
The link is correct, but the invoice is not at the right place. It should be in the user000blabla folder.
Is something in the admin log stating that the folder could not be created?

**Comment by kreossino** [comment]
the directory is created, but the files not copyied in this dir but in root.
i think isn't present the  "/ "  on the name because i see  the file 
namedirnamefile.pdf  not namedir/namefile.pdf
