### ISSUE TITLE
Invalid Token using PayPal REST SandBox

### ISSUE THREAD

**Issue by Cybernatus** [e107inc/vstore#87]
Ohayo,

I'm currently encountering an issue with PayPal REST Gateway while going back from PayPal's Sandbox to confirm a payment. 
The result always ends with the following error => "Token signature verification failed". 
I've actually settled up many kind of configurations to segragate this error but it always appears anyway.

This issue is probably related to this fix merged on Omnipay's repository earlier in May : https://github.com/thephpleague/omnipay-paypal/commit/519db61b32ff0c1e56cbec94762b970ee9674f65 . 

As the code of VStore differs from it, I can't apply the change by myself to see if it fix this issue (As I wouldn't know the mess I'd going to do). So I'm now going straight to you guys to see if it's truly the same issue and it it would be possible to fix it right away. 

In hope it would be the case,
With all the best,
Cybernatus.

EDIT : Server logs also return the following error during process 

`[Wed Aug 29 22:51:54.403914 2018] [:error] [pid 10368] [client ********:64139] PHP Fatal error:  Uncaught Omnipay\\Common\\Exception\\InvalidRequestException: The payerId parameter is required in /e107_plugins/vstore/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:213\nStack trace:\n#0 /e107_plugins/vstore/vendor/omnipay/paypal/src/Message/RestCompletePurchaseRequest.php(58): Omnipay\\Common\\Message\\AbstractRequest->validate('transactionRefe...', 'payerId')\n#1 /e107_plugins/vstore/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php(676): Omnipay\\PayPal\\Message\\RestCompletePurchaseRequest->getData()\n#2 /e107_plugins/vstore/vstore.class.php(1456): Omnipay\\Common\\Message\\AbstractRequest->send()\n#3 /e107_plugins/vstore/vstore.class.php(420): vstore->processGateway('return')\n#4 /e107_plugins/vstore/vstore.class.php(226): vstore->process()\n#5 /e107_plugins/vstore/vstore.php(36): vstore->init()\n#6 /var/site/lanex/index.php(69): include_once('...')\n#7 {main}\n  th in /e107_plugins/vstore/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php on line 213, referer: https://*******/vstore/checkout/return/?paymentId=PAY-*********Y&token=EC-**********&PayerID=***********`

**Comment by SimSync** [comment]
It looks like that we need to update the omnipay repos to the latest version as it doesn't make much sense to fix the issue in the older version.
We still need to check other dependencies.

**Comment by poonamsatani** [comment]
jhbj
