### ISSUE TITLE
Database Utilities - SQL Verification

### ISSUE THREAD

**Issue by burzintaj** [e107inc/vstore#88]
Table: vstore_cart
Field: cart_lastupdate
Status: Mismatch

Currently
DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
should be
DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

**Comment by SimSync** [comment]
This seems to be fixed in e107 v2.2.0

**Comment by SimSync** [comment]
@burzintaj Could you please check if this is still an issue for you? Otherwise please close this issue. Thanks!
