### ISSUE TITLE
Product variation requirement

### ISSUE THREAD

**Issue by realmontazeri** [e107inc/vstore#90]
It's still possible to add products to the card without selecting a required variation item so this must be a bug.

**Comment by SimSync** [comment]
The "Required" setting is pretty useless. I think it should get removed in the future.
Just make sure the variations are not empty or a single space.

**Comment by SimSync** [comment]
@burzintaj Is there anything that has to be done here?

**Comment by oui3kings** [comment]
I'd like to suggest the ability to add more than 2 variations to a product

**Comment by SimSync** [comment]
@oui3kings I can't imagine how it should work to have more than 2 variations. Each variation adds a dimension to the inventory array.
For example:
1 variation (Size: XL, XS) means that the inventory has 1 dimension for the number of products per size (e.g. inventory = 

| Size | XL | XS |
| - | -- | -- |
|  | 10 | 15 |

2 variations (Size: XL, XS / Color: Black, White) means the inventory has 2 dimenstions:
e.g. inventory = 

| Color | Size | XL | XS |
| - | - | -- | -- |
| Black | | 10 Black in XL | 15 Black in XS |
| White | | 22 White in XL | 5 White in XS |

Adding a third variations is not generally a problem for the data, but to display it in a table, to be able to set the inventory vor each combination? A table is by nature only 2 dimensional. 

Any idea how this can be achieved?

**Comment by oui3kings** [comment]
Just wondering because I am currently using the easyshop plugin and some of the items I have have 5 variations. In some of those instances I am using a variation for different shipping options. I could omit one of those and get to 4 variations but there are some items I have that need 4 maybe 5 variations.

**Comment by SimSync** [comment]
I don't think that that easyshop is maintaining the inventory based on product variation combinations.
But that's what vstore does.

**Comment by SimSync** [comment]
See PR #106

**Comment by realmontazeri** [comment]
This option doesn't exist in the latest version anymore, It was needed to improve and not to remove.
