### ISSUE TITLE
Error installing / creating vstore_cart table

### ISSUE THREAD

**Issue by oui3kings** [e107inc/vstore#98]
Install resulting in no vstore_cart table. Manual creation attempt results in following error

Error
SQL query:

CREATE TABLE e107_vstore_cart(

 `cart_id` INT( 11 ) NOT NULL AUTO_INCREMENT ,
 `cart_session` VARCHAR( 250 ) DEFAULT NULL ,
 `cart_e107_user` VARCHAR( 250 ) DEFAULT NULL ,
 `cart_status` VARCHAR( 250 ) DEFAULT NULL ,
 `cart_item` INT( 11 ) DEFAULT NULL ,
 `cart_item_vars` TEXT,
 `cart_item_tax_class` VARCHAR( 20 ) NOT NULL DEFAULT  'standard',
 `cart_qty` INT( 11 ) DEFAULT NULL ,
 `cart_paystat` VARCHAR( 250 ) DEFAULT NULL ,
 `cart_paydate` VARCHAR( 250 ) DEFAULT NULL ,
 `cart_paytrans` VARCHAR( 250 ) DEFAULT NULL ,
 `cart_paygross` DECIMAL( 10, 2 ) NOT NULL DEFAULT  '0.00',
 `cart_payshipping` DECIMAL( 10, 2 ) NOT NULL DEFAULT  '0.00',
 `cart_payshipto` TEXT,
 `cart_lastupdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
PRIMARY KEY (  `cart_id` )
) ENGINE = MYISAM
MySQL said: Documentation

#1067 - Invalid default value for 'cart_lastupdate'

**Comment by SimSync** [comment]
What is the MySQL version?

**Comment by CaMer0n** [comment]
5.5.43-37.2

**Comment by SimSync** [comment]
This version should support the current_timestamp function... Strange.

**Comment by CaMer0n** [comment]
@oui3kings I'm going to close this since too many changes have occurred since this issue was created. However, if this issue occurs again, please let me know and I'll re-open it.
