### ISSUE TITLE
e107\vstore SQL bug

### ISSUE THREAD

**Issue by Bepo2902** [e107inc/vstore#99]
![grafik](https://user-images.githubusercontent.com/46347624/53288793-083e7600-3785-11e9-8b09-442e8b6e65f0.png)

another user mentioned that "it appears there’s a bug in the plugin’s _sql.php file. Those two () should not be in there."

**Comment by SimSync** [comment]
Do you have the last 2 Screenshots as single files? I'm unable to identify the text in that images on your image above.

**Comment by Moc** [comment]
They are in the vstore Gitter

**Comment by SimSync** [comment]
Ok, read thru the chat on gitter and could you please also post your database version and if you are using MySQL or Mariadb?

**Comment by CaMer0n** [comment]
@SimSync I'm on MariaDB 10.3.10 and I can reproduce the same issue.  Pasting this screenshot below as a (legible) reference. 

![image](https://user-images.githubusercontent.com/2825679/53293393-f01c2600-3787-11e9-9b76-9201e7c508b1.png)

**Comment by CaMer0n** [comment]
I've committed a fix. @SimSync Please let me know if it causes issues with your set up.

**Comment by SimSync** [comment]
@CaMer0n As expected, MySQL returns the `CREATE TABLE` call without the brackets at the end of `CURRENT_TIMESSTAMP`. Even creating the table with the changed definition doesn't change this behaviour.
I tried also to replace `CURRENT_TIMESTAMP` with `NOW()` (`CURRENT_TIMESTAMP` is a synonym for `NOW()` as stated in the MySQL docs) didn't change anything. The `CREATE TABLE` call returns always `CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP` without the brackets.

I would propose a simple `str_replace("CURRENT_TIMESTAMP()", "CURRENT_TIMESTAMP", strtoupper($m[6][$k]))` on line 961 in file db_verify_class.php to handle the different behaviour between MySQL and MariaDB.

**Comment by CaMer0n** [comment]
@SimSync Thanks. How about something inside diffStructurePermissive($expected, $actual) ?
I just added something for the JSON alias in MySQL 5.7+

**Comment by SimSync** [comment]
@CaMer0n Yes, why not. Will you add it or should i?

**Comment by SimSync** [comment]
@CaMer0n Have created a PR with a change on `diffStructurePermissive($expected, $actual)`.

**Comment by SimSync** [comment]
@Bepo2902 Please update e107 and also vstore from git and check if the issue is gone.

**Comment by Bepo2902** [comment]
Thank you, works like a charme.
